### ISSUE TITLE
Issue with --input_bam_dir

### ISSUE THREAD

**Issue by Anouk-vw** [W-L/deviaTE#15]
Hi,

I succesfully ran deviaTE on individual fastq files and I am happy with the results. Now I wanted to run the tool again on a directory of files, I tried to use --input_fq_dir /path/to/dir and --input_bam_dir /path/to/dir, however in both cases the program reports that the argument /path/to/dir is not recognized. See command and output bellow. Are you familiar with this issue? I would like to run the program on multiple files. 

Command:
deviaTE --library {TE_lib.fa} --threads 10 --families {Heli1consensus} --single_copy_genes {ETFg} --input_bam_dir /path/to/dir

Output:
usage: deviaTE [-h] [--library LIBRARY] [--read_type {phred+64,phred+33}] [--min_read_len MIN_READ_LEN] [--quality_threshold QUALITY_THRESHOLD]
               [--min_alignment_len MIN_ALIGNMENT_LEN] [--threads THREADS] [--no_delet_detect] --families FAMILIES [--annotation ANNOTATION] [--no_freq_corr]
               [--hq_threshold HQ_THRESHOLD] [--minID MINID] [--rpm | --single_copy_genes SINGLE_COPY_GENES] [--free_yaxis]
               (--input_fq INPUT_FQ | --input_bam INPUT_BAM | --input_fq_dir | --input_bam_dir)

**deviaTE: error: unrecognized arguments: /path/to/dir**

**Comment by W-L** [comment]
Hi,
thanks for getting in touch! The arguments to run on a directory just use the current working directory as input, instead of specifying a path. I.e. the argument works as a flag and just grab all fastq/bam files that are present in the current directory. Does that work for your setup? If not, I'm happy to change it to work as you tried to use it, which would make more sense to be honest.
Best wishes!

**Comment by Anouk-vw** [comment]
Thanks a lot for the fast reply! That makes sense, I missed that part. I can run it from the directory I want to use, no problem.
