### ISSUE TITLE
Genome Size

### ISSUE THREAD

**Issue by CGNAT** [W-L/deviaTE#2]
Hello,

I am hoping to perform analysis on the TE family radiation within the human genome. Is this possible using this tool? The D.melanogaster is 132 million, compared to the human at 3.2 billion. Is there some other way I should be going about this? 

I have whole genome sequences, but deviaTE does not seem to progress past the point of trimming the reads, even when run on an HPC and given 6 days. Am I doing something incorrect?

**Comment by W-L** [comment]
Hello CGNAT!
Thank you very much for your message. It is definitely possible to use our tool with reads from the human genome (Fig. S7 of our manuscript supplement has some very basic examples of TEs in humans). I don't think there is a mistake but it might be easier to judge with a bit more information. What is the command you used to run the program? And what are the input files you used? If it is simply a speed issue, there are two things that could help to make it easier:

1) It might be more efficient to use an alignment procedure other than the one implemented in deviaTE (e.g. Bowtie2, minimap2 etc.) And align your sequencing reads to the TE consensus sequences before analysis with deviaTE. We did not test all of the aligners and they might produce certain biases (e.g. edge effects) when aligning to short TE reference sequences, but they should certainly be faster.
Then you can start deviaTE with the option `--input_bam`, instead of `--input_fq`, as you would with the raw sequencing reads.

2) If you are not specifically interested in studying internal deletions in TEs, you can turn off their detection by running deviaTE with the option `--no_delet_detect` This should speed up the analysis by a lot.

Hope this helps, let me know how it's going!
Lukas

**Comment by CGNAT** [comment]
Thank you! I managed to solve the issue by mapping with bwa and then piping to deviaTE like you suggested. Thank you for your help!

**Comment by W-L** [comment]
Great to hear that it worked out! Thank for getting back to us

**Comment by r-mashoodh** [comment]
> Thank you! I managed to solve the issue by mapping with bwa and then piping to deviaTE like you suggested. Thank you for your help!

would you mind sharing what parameters you ended up using?
