### ISSUE TITLE
condo create problems with samtools

### ISSUE THREAD

**Issue by LisaBlazek** [W-L/deviaTE#8]
hallo!
i have a problem with samtools after creating the condo environment:
```
conda create deviaTE -c r -c defaults -c conda-forge -c bioconda -c w-l -n deviaTE_env
#and
#like you suggested in another ticket
conda create deviaTE==0.3.7 -c r -c defaults -c conda-forge -c bioconda -c w-l -n deviaTE_env 

```

if i want to run samtools in the deviaTE_env i get an error:
**_**samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory**_**

i found out that this is an known conda bug and tried to update samtools 
```
conda install -c bioconda samtools=1.9 --force-reinstall
#or 
conda config --add channels bioconda
conda config --add channels conda-forge
conda install samtools==1.11
```
but nothing helped. maybe you have some insight? i was really looking forward on using this program!
kind regards,
lisa

**Comment by W-L** [comment]
Hi Lisa,
Thanks for getting in touch! This is something I have seen a few times before, especially on MacOS.
As far as I understand, this is because samtools has some trouble with missing links to the mentioned libcrypto library.

Here's what helped to solve this in the past: 
- Make sure that openssl is installed system-wide
- then link the missing libraries manually

```
brew install openssl
[or]
conda install openssl

ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
```
I hope this helps, please keep me updated!
Lukas

**Comment by LisaBlazek** [comment]
hello!
i tried to install openssl and this kinda worked, openssl was in my path but i could not locate the two missing libraries.
as an alternative i tried to install the program with pip and used it on you test data and this worked, i got the same pdf.
so i think i'm gonna close the ticket.
thank you for your fast reply and help!!!
